#!/bin/bash

hostname="${1:-$(hostname)}"
mailto="fho"

opts="-v --humanize-numbers"
maxage_sec=$(( 60 * 60 * 24 * 7))

log()
{
	echo "$@"
}

[ -z "$hostname" ] && {
	echo "usage: $0 HOSTNAME"
	exit 1
}

curts=$(date +%s)
archives=$(tarsnap --list-archives |grep "$hostname-")
backup_deleted=0
for archive in $archives; do
	ts=$(echo $archive|grep -o "\-[0-9]*"|grep -o "[0-9]*")
	archive_name=$(echo $archive|grep  "[[:alpha:]-]*")
	if [ $(echo $archive|grep $archive_name|wc -l) -le 1 ]; then
		# don't delete archive if it is the only one for the
		# destination
		continue
	fi
	if [ -z "$ts" ];then
		log "No timestamp found in archive name $archive"
		continue
	fi
	ts=$(date -d $ts +%s)
	if [ $(($curts - $ts)) -ge $maxage_sec ]; then
		log "Deleting archive $archive"
		tarsnap $cachedir $opts -d\
			-f "$archive" 2>&1
		backup_deleted=1
	fi
done
if [ $backup_deleted -eq 1 ]; then
	subject="$hostname Backups deleted"
else
	subject="$hostname Backup statistics (no backups deleted)"
fi

tarsnap --print-stats
